const GET_POKEMONS = "GET_POKEMONS";
const GET_DETAIL = "GET_DETAIL";
const CLEAR_DETAIL_STATE = "CLEAR_DETAIL_STATE";
const GET_TYPES = "GET_TYPES";
const POST_POKEMON = "POST_POKEMON";
const FILTER_BY_TYPE = "FILTER_BY_TYPE";
const GET_POKEMON_NAME = "GET_POKEMON_NAME";
const ORDER_BY_NAME = "ORDER_BY_NAME";
const FILTER_BY_ATTACK = "FILTER_BY_ATTACK";
const FILTER_BY_DEFENSE = "FILTER_BY_DEFENSE";
const FILTER_BY_HP = "FILTER_BY_HP";
const FILTER_BY_SPEED = "FILTER_BY_SPEED";
const DELETE_POKEMON = "DELETE_POKEMON"

export {
    GET_POKEMONS,
    GET_DETAIL,
    CLEAR_DETAIL_STATE,
    GET_TYPES,
    POST_POKEMON,
    FILTER_BY_TYPE,
    GET_POKEMON_NAME,
    ORDER_BY_NAME,
    FILTER_BY_ATTACK,
    FILTER_BY_DEFENSE,
    FILTER_BY_HP,
    FILTER_BY_SPEED,
    DELETE_POKEMON
};