const GET_POKEMONS = "GET_POKEMONS";
const GET_DETAIL = "GET_DETAIL";
const CLEAR_DETAIL_STATE = "CLEAR_DETAIL_STATE";
const GET_TYPES = "GET_TYPES";

export {
    GET_POKEMONS,
    GET_DETAIL,
    CLEAR_DETAIL_STATE,
    GET_TYPES,
};