const GET_POKEMONS = "GET_POKEMONS";
const GET_DETAIL = "GET_DETAIL";
const CLEAR_DETAIL_STATE = "CLEAR_DETAIL_STATE";
const GET_TYPES = "GET_TYPES";
const POST_POKEMON = "POST_POKEMON";
const FILTER_BY_TYPE = "FILTER_BY_TYPE";

export {
    GET_POKEMONS,
    GET_DETAIL,
    CLEAR_DETAIL_STATE,
    GET_TYPES,
    POST_POKEMON,
    FILTER_BY_TYPE
};